trigger:
  batch: true
  branches:
    include:
      - "main"

variables:
- name: SolutionBaseName
  value: __SolutionBaseName__
- name: BuildConfiguration
  value: release
- name: BuildPlatform
  value: any cpu

pool:
  name: DAS - Continuous Integration Agents
  workspace:
    clean: all

resources:
  repositories:
  - repository: self
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/tags/0.4.63
    endpoint: SkillsFundingAgency

stages:
- stage: QualityAndUnitTests
  jobs:
  - template: pipeline-templates/job/quality-unit-test.yml
- stage: Release
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
  jobs:
  - template: pipeline-templates/job/release.yml

