jobs:
- job: IntegrationTestsLinux
  displayName: "Integration Tests - Linux"
  pool:
    name: "DAS - Continuous Integration"
    demands:
      - agent.OS -equals Linux
  workspace:
    clean: all
  steps:
  ##TO DO: remove this task
  - pwsh: Get-ChildItem ENV:* | Sort-Object Name | Format-Table -AutoSize
  # note this can be replaced with a PesterContainer after upgrading to Pester v5.x - https://stackoverflow.com/a/65790776/7360635
  - task: PowerShell@2
    displayName: 'PowerShell: Set GitHubPatToken environment variable'
    inputs:
      targetType: inline
      script: |
        Set-Location -Path Env:
        Set-Item -Path GitHubPatToken -Value $(GitHubPatToken)
  - task: PowerShell@2
    displayName: 'PowerShell: Invoke-IntegrationTests.ps1'
    inputs:
      filePath: "tests/Invoke-Tests.ps1"
      arguments: '-TestType "Integration"'
      pwsh: true
  - task: PublishTestResults@2
    displayName: Publish Test Results **/TEST-*.xml
    inputs:
      testResultsFormat: NUnit
      testResultsFiles: "**/TEST-*.xml"
    condition: succeededOrFailed()
