jobs:
- deployment: GitHubRelease
  displayName: Create Release in GitHub
  pool:
    name: DAS - Continuous Deployment Agents
  environment: GitHub
  strategy:
    runOnce:
      deploy:
        steps:
        - task: GitHubRelease@0
          inputs:
            gitHubConnection: SFA
            repositoryName: $(Build.Repository.Name)
            action: create
            target: $(Build.SourceVersion)
            tagSource: manual
            tag: $(Build.BuildNumber)
            addChangeLog: true

